/**
 * WhatsAppShare — generates a pre-formatted WhatsApp message with
 * key feasibility report or EMI data and opens wa.me to share it.
 *
 * Variants:
 *   "report"  — shares feasibility report summary.
 *   "emi"     — shares EMI reminder for a specific loan.
 */

function formatINR(n) {
  const num = Number(n || 0);
  if (num >= 100000) return '₹' + (num / 100000).toFixed(2) + ' Lakh';
  return '₹' + num.toLocaleString('en-IN');
}

function buildReportMessage(report) {
  const fin = report?.financials || {};
  const cat = report?.business_category || 'Business';
  const loc = report?.display_name || report?.location || '';
  const scheme = fin.selected_scheme || 'Government Scheme';
  const projectCost = formatINR(fin.project_cost);
  const loan = formatINR(fin.loan_amount);
  const margin = formatINR(fin.margin_contribution);
  const rate = fin.interest_rate_pct || '—';
  const tenure = fin.tenure_months ? Math.round(fin.tenure_months / 12) + ' years' : '—';

  return [
    `📊 *FinGrow Business Feasibility Report*`,
    ``,
    `🏪 *Business:* ${cat}`,
    `📍 *Location:* ${loc}`,
    ``,
    `💰 *Financial Summary:*`,
    `   Total Project Cost: ${projectCost}`,
    `   Your Contribution (10%): ${margin}`,
    `   Government Loan (90%): ${loan}`,
    ``,
    `🏦 *Scheme:* ${scheme}`,
    `   Interest Rate: ${rate}% p.a.`,
    `   Tenure: ${tenure}`,
    ``,
    `✅ Report generated by FinGrow — AI Business Advisory for Rural Micro-Entrepreneurs.`,
    `🌐 https://fingrow.in`,
  ].join('\n');
}

function buildEMIMessage(loan) {
  const name = loan?.name || 'Loan';
  const id = loan?.id || '';
  const emi = formatINR(loan?.amount || loan?.monthly_emi);
  const outstanding = formatINR(loan?.outstanding_principal);
  const dueDate = loan?.next_due_date || loan?.date || 'upcoming';

  return [
    `🔔 *FinGrow EMI Reminder*`,
    ``,
    `🏦 *Loan:* ${name}`,
    `📋 *Ref:* ${id}`,
    `💵 *Next EMI:* ${emi}`,
    `📅 *Due Date:* ${dueDate}`,
    `💰 *Outstanding:* ${outstanding}`,
    ``,
    `Pay on time to maintain your credit score! ✅`,
    `— FinGrow Advisory`,
  ].join('\n');
}

function openWhatsApp(text, phoneNumber) {
  const encoded = encodeURIComponent(text);
  const url = phoneNumber
    ? `https://wa.me/91${phoneNumber}?text=${encoded}`
    : `https://wa.me/?text=${encoded}`;
  window.open(url, '_blank', 'noopener,noreferrer');
}

/**
 * WhatsAppShare button component.
 *
 * Props:
 *   variant       — "report" or "emi"
 *   report        — feasibility report data (for variant="report")
 *   loan          — loan data (for variant="emi")
 *   phoneNumber   — optional 10-digit mobile to pre-fill recipient
 *   compact       — if true, shows only icon (no text label)
 *   className     — extra CSS classes
 */
export default function WhatsAppShare({
  variant = 'report',
  report,
  loan,
  phoneNumber,
  compact = false,
  className = '',
}) {
  const handleClick = () => {
    const text = variant === 'emi'
      ? buildEMIMessage(loan)
      : buildReportMessage(report);
    openWhatsApp(text, phoneNumber);
  };

  return (
    <button
      type="button"
      onClick={handleClick}
      className={`whatsapp-share-btn ${compact ? 'whatsapp-share-btn--compact' : ''} ${className}`}
      title="Share via WhatsApp"
      aria-label="Share via WhatsApp"
    >
      <svg viewBox="0 0 24 24" width="20" height="20" fill="currentColor" className="shrink-0">
        <path d="M17.472 14.382c-.297-.149-1.758-.867-2.03-.967-.273-.099-.471-.148-.67.15-.197.297-.767.966-.94 1.164-.173.199-.347.223-.644.075-.297-.15-1.255-.463-2.39-1.475-.883-.788-1.48-1.761-1.653-2.059-.173-.297-.018-.458.13-.606.134-.133.298-.347.446-.52.149-.174.198-.298.298-.497.099-.198.05-.371-.025-.52-.075-.149-.669-1.612-.916-2.207-.242-.579-.487-.5-.669-.51-.173-.008-.371-.01-.57-.01-.198 0-.52.074-.792.372-.272.297-1.04 1.016-1.04 2.479 0 1.462 1.065 2.875 1.213 3.074.149.198 2.096 3.2 5.077 4.487.709.306 1.262.489 1.694.625.712.227 1.36.195 1.871.118.571-.085 1.758-.719 2.006-1.413.248-.694.248-1.289.173-1.413-.074-.124-.272-.198-.57-.347m-5.421 7.403h-.004a9.87 9.87 0 01-5.031-1.378l-.361-.214-3.741.982.998-3.648-.235-.374a9.86 9.86 0 01-1.51-5.26c.001-5.45 4.436-9.884 9.888-9.884 2.64 0 5.122 1.03 6.988 2.898a9.825 9.825 0 012.893 6.994c-.003 5.45-4.437 9.884-9.885 9.884m8.413-18.297A11.815 11.815 0 0012.05 0C5.495 0 .16 5.335.157 11.892c0 2.096.547 4.142 1.588 5.945L.057 24l6.305-1.654a11.882 11.882 0 005.683 1.448h.005c6.554 0 11.89-5.335 11.893-11.893a11.821 11.821 0 00-3.48-8.413z" />
      </svg>
      {!compact && <span>Share on WhatsApp</span>}
    </button>
  );
}

export { buildReportMessage, buildEMIMessage, openWhatsApp };
